# Generated by Django 5.1.7 on 2025-03-29 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_open_slots', models.JSONField(default=dict)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_slots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый ученик', max_length=100, verbose_name='Имя ученика')),
                ('bitrix_link', models.URLField(blank=True, max_length=500)),
                ('lesson_balance', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс уроков')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.teacher')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, verbose_name='Имя студента')),
                ('course', models.CharField(default='Не выбран', max_length=100, verbose_name='Курс')),
                ('lesson_type', models.CharField(choices=[('single', 'Разовый'), ('recurring', 'Регулярный')], max_length=10, verbose_name='Тип урока')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Проведён'), ('canceled', 'Отменён')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('schedule', models.JSONField(default=list, help_text='Формат: [{"day": "monday", "time": "14:00"}, {"day": "wednesday", "time": "16:00"}]', verbose_name='Расписание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала повторений')),
                ('lesson_topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема урока')),
                ('lesson_notes', models.TextField(blank=True, null=True, verbose_name='Комментарий преподавателя')),
                ('homework', models.TextField(blank=True, null=True, verbose_name='Домашнее задание')),
                ('cancel_reason', models.TextField(blank=True, default=None, null=True, verbose_name='Причина отмены урока')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время проведения')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время проведения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_hours_start', models.IntegerField(default=9)),
                ('working_hours_end', models.IntegerField(default=18)),
                ('theme', models.CharField(default='light', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
