# Generated by Django 5.1.7 on 2025-03-31 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Заметка (например, "Бабушка Алла")')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной номер')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='core.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
                'ordering': ['-is_primary', 'id'],
            },
        ),
    ]
