# Generated by Django 5.1.7 on 2025-03-30 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='start_date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя ученика'),
        ),
        migrations.AlterField(
            model_name='balanceoperation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='schedule',
            field=models.JSONField(default=list, help_text='Поле для постоянного расписания', verbose_name='Регулярное расписание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время урока'),
        ),
    ]
