# Generated by Django 5.1.7 on 2025-03-25 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='student',
            name='bitrix_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Новый ученик', max_length=100, verbose_name='Имя ученика'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='не выбрано', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student'),
        ),
    ]
