# Generated by Django 5.1.7 on 2025-03-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_balanceoperation_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя ученика'),
        ),
    ]
