# Generated by Django 5.1.7 on 2025-03-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_timeslot_options_remove_student_parent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Отметьте для регулярных занятий', verbose_name='Регулярный урок'),
        ),
    ]
