# Generated by Django 5.1.7 on 2025-04-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacherpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherpayment',
            options={'verbose_name': 'Выпплата преподавателю', 'verbose_name_plural': 'Выплаты преподавателям'},
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='week_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
