# Generated by Django 5.1.7 on 2025-03-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timeslot_is_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='duration',
        ),
    ]
