# Generated by Django 5.1.7 on 2025-03-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lesson_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='schedule',
            field=models.JSONField(default=list, verbose_name='Расписание'),
        ),
    ]
