# Generated by Django 5.1.7 on 2025-03-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_lesson_start_date_alter_lesson_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='schedule',
            field=models.JSONField(default=list, help_text='Поле для постоянного расписания', verbose_name='Регулярное расписание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время урока'),
        ),
    ]
