# Generated by Django 5.1.7 on 2025-03-26 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_timeslot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lesson_balance',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс уроков'),
        ),
    ]
