# Generated by Django 5.1.7 on 2025-04-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_teacherpayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherpayment',
            name='week_end_date',
            field=models.DateField(),
        ),
    ]
