# Generated by Django 5.1.7 on 2025-03-26 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_lesson_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('completed', 'Проведен'), ('canceled', 'Отменен'), ('modified', 'Изменен')], max_length=50, verbose_name='Действие')),
                ('old_balance', models.IntegerField(verbose_name='Было уроков')),
                ('new_balance', models.IntegerField(verbose_name='Стало уроков')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='core.timeslot', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student', verbose_name='Студент')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Лог урока',
                'verbose_name_plural': 'Логи уроков',
                'ordering': ['-created_at'],
            },
        ),
    ]
