# Generated by Django 5.1.7 on 2025-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lessonlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала регулярных уроков'),
        ),
    ]
