# Generated by Django 5.1.7 on 2025-03-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timeslot_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='timeslot',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проведения'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='homework',
            field=models.TextField(blank=True, null=True, verbose_name='Домашнее задание'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='lesson_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к уроку'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='lesson_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема урока'),
        ),
    ]
