# Generated by Django 5.1.7 on 2025-04-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_populate_balance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperation',
            name='balance_after',
            field=models.IntegerField(default=0, verbose_name='Баланс после операции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balanceoperation',
            name='balance_before',
            field=models.IntegerField(default=0, verbose_name='Баланс до операции'),
            preserve_default=False,
        ),
    ]
