# Generated by Django 5.1.7 on 2025-03-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_timeslot_options_timeslot_completed_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeSlot',
            new_name='Lesson',
        ),
    ]
