# Generated by Django 5.1.7 on 2025-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_alter_balanceoperation_balance_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='allow_negative_once',
            field=models.BooleanField(default=False, verbose_name='Разрешить одно списание в минус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс уроков'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('single', 'Разовый'), ('recurring', 'Регулярный'), ('demo', 'Вводный')],
                                   max_length=10, verbose_name='Тип урока'),
        ),
    ]
