# Generated by Django 5.1.7 on 2025-04-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_client_allow_negative_once_alter_client_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_reliable',
            field=models.BooleanField(choices=[(True, 'Надёжный'), (False, 'Ненадёжный')], default=True,
                                      help_text='Определяет, можно ли рассчитывать на этот урок',
                                      verbose_name='Статус урока'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['balance'], name='core_client_balance_576f6c_idx'),
        ),
    ]
