# Generated by Django 5.1.7 on 2025-04-15 10:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0010_lesson_is_reliable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_reliable',
        ),
    ]
