# Generated by Django 5.1.7 on 2025-03-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_lesson_is_recurring_remove_lesson_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя студента'),
        ),
    ]
