# Generated by Django 5.1.7 on 2025-04-16 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_alter_teacherpayment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpayment',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты до'),
        ),
    ]
