# Generated by Django 5.1.7 on 2025-04-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_teacherpayment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceoperation',
            name='amount',
            field=models.IntegerField(verbose_name='Количество уроков'),
        ),
    ]
