# Generated by Django 5.1.7 on 2025-05-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_alter_balanceoperation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='previous_topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема предыдущего урока'),
        ),
    ]
