# Generated by Django 5.1.7 on 2025-05-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_lesson_previous_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='previous_comment',
            field=models.CharField(blank=True, max_length=255, null=True,
                                   verbose_name='Комментарий к предыдущему уроку'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='previous_homework',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ДЗ предыдущего урока'),
        ),
    ]
