# Generated by Django 5.1.7 on 2025-05-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_lesson_previous_comment_lesson_previous_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='platform',
            field=models.CharField(choices=[('google-meet', 'Google Meet'), ('zoom', 'Zoom')], default='google-meet',
                                   max_length=15, verbose_name='Платформа'),
        ),
    ]
