# Generated by Django 5.1.7 on 2025-05-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0017_lesson_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='google_meet_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Google Meet ссылка'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zoom_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Zoom ссылка'),
        ),
    ]
