# Generated by Django 5.1.7 on 2025-06-24 07:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_teacher_google_meet_link_teacher_zoom_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='balanceoperation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата операции'),
        ),
    ]
