# Generated by Django 5.1.7 on 2025-06-24 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_client_deleted_client_deleted_by_cascade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedClient',
            fields=[
            ],
            options={
                'verbose_name': 'Удалённый клиент',
                'verbose_name_plural': 'Корзина клиентов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.client',),
        ),
    ]
