# Generated by Django 5.1.7 on 2025-06-24 19:13

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_deletedclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='В формате +79161234567',
                                                                 max_length=128, region='RU', verbose_name='Телефон'),
        ),
    ]
