# Generated by Django 5.1.7 on 2025-06-24 19:30

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_client_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_phone',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='В международном формате (+79161234567)',
                                                                 max_length=128, region=None,
                                                                 verbose_name='Номер телефона'),
        ),
    ]
