# Generated by Django 5.1.7 on 2025-06-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_remove_client_client_phone_alter_phonenumber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('teacher', 'Преподаватель'), ('student', 'Ученик')],
                                   max_length=10, null=True, verbose_name='Кто отменил урок'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_custom_reason',
            field=models.BooleanField(default=False, verbose_name='Кастомная причина'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Текст причины отмены'),
        ),
    ]
