# Generated by Django 5.1.7 on 2025-06-25 10:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0023_lesson_cancelled_by_lesson_is_custom_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='canceled_at',
        ),
    ]
