# Generated by Django 5.1.7 on 2025-06-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_remove_lesson_canceled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openslots',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='open_slots',
                                       to='core.teacher'),
        ),
    ]
