# Generated by Django 5.1.7 on 2025-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_alter_openslots_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('teacher', 'Преподаватель'), ('student', 'Ученик')],
                                   max_length=25, null=True, verbose_name='Кто отменил урок'),
        ),
    ]
