# Generated by Django 5.1.7 on 2025-09-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_alter_lesson_cancelled_by'),
        ('materials', '0005_alter_guide_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='materials.course',
                                         verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='openslots',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='open_slots', to='core.teacher'),
        ),
    ]
