# Generated by Django 5.1.7 on 2025-10-04 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_teacher_courses_alter_openslots_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(
                    choices=[('advertising', 'Реклама'), ('software', 'Софт/Подписки'), ('taxes', 'Налоги'),
                             ('other', 'Другое')], max_length=20, verbose_name='Категория расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Расход школы',
                'verbose_name_plural': 'Расходы школы',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
