# Generated by Django 5.1.7 on 2025-10-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0028_schoolexpense_alter_lesson_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeMoneyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Баланс свободных денег',
                'verbose_name_plural': 'Баланс свободных денег',
            },
        ),
    ]
