# Generated by Django 5.1.7 on 2025-10-05 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0029_freemoneybalance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeMoneyBalance',
        ),
    ]
