# Generated by Django 5.1.7 on 2025-10-05 15:51

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_delete_freemoneybalance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('reserved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('free_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('last_event_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(
                    choices=[('INCOME', 'Доход'), ('EXPENSE', 'Расход'), ('RESERVE', 'Резервирование'),
                             ('RELEASE', 'Снятие резерва'), ('ADJUSTMENT', 'Корректировка')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14,
                                               validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True,
                                                 help_text='Опциональный уникальный ключ от внешней системы для идемпотентности',
                                                 max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='finance_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_financ_created_1a2878_idx'),
                            models.Index(fields=['event_type'], name='core_financ_event_t_d0e226_idx')],
            },
        ),
    ]
