# Generated by Django 5.1.7 on 2025-10-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0031_financesnapshot_financeevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeevent',
            name='event_type',
            field=models.CharField(choices=[('INCOME', 'Доход'), ('EXPENSE', 'Расход'), ('RESERVE', 'Резервирование'),
                                            ('RELEASE', 'Снятие резерва')], max_length=20),
        ),
    ]
