# Generated by Django 5.1.7 on 2025-10-09 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0032_alter_financeevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeevent',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='FinanceSnapshot',
        ),
        migrations.DeleteModel(
            name='SchoolExpense',
        ),
        migrations.DeleteModel(
            name='FinanceEvent',
        ),
    ]
