# Generated by Django 5.1.7 on 2025-10-09 11:15

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('reserved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('free_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('last_event_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(
                    choices=[('advertising', 'Реклама'), ('software', 'Софт/Подписки'), ('taxes', 'Налоги'),
                             ('other', 'Другое')], max_length=20, verbose_name='Категория расхода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата расхода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Расход школы',
                'verbose_name_plural': 'Расходы школы',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='FinanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(
                    choices=[('INCOME', 'Доход'), ('EXPENSE', 'Расход'), ('RESERVE', 'Резервирование'),
                             ('RELEASE', 'Снятие резерва')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14,
                                               validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True,
                                                 help_text='Опциональный уникальный ключ от внешней системы для идемпотентности',
                                                 max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 related_name='finance_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='finance_fin_created_01ac58_idx'),
                            models.Index(fields=['event_type'], name='finance_fin_event_t_b98dfd_idx')],
            },
        ),
    ]
