# Generated by Django 5.1.7 on 2025-10-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Финансовое событие',
                     'verbose_name_plural': 'Финансовые события'},
        ),
        migrations.AlterModelOptions(
            name='financesnapshot',
            options={'ordering': ['-created_at'], 'verbose_name': 'Снапшот баланса',
                     'verbose_name_plural': 'Снапшоты баланса'},
        ),
        migrations.AddField(
            model_name='financesnapshot',
            name='last_event_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='snapshots', to='finance.financeevent',
                                    verbose_name='Последнее событие'),
        ),
    ]
