# Generated by Django 5.1.7 on 2025-10-10 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0002_alter_financeevent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financesnapshot',
            name='last_event_id',
        ),
    ]
