# Generated by Django 5.1.7 on 2025-04-18 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('cover', models.FileField(blank=True, upload_to='courses/covers/', verbose_name='Обложка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название уровня')),
                ('description', models.TextField(blank=True, verbose_name='Описание уровня')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels',
                                             to='materials.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('html_file',
                 models.FileField(blank=True, null=True, upload_to='guides/html/', verbose_name='HTML файл')),
                ('assets',
                 models.FileField(blank=True, null=True, upload_to='guides/assets/', verbose_name='Ресурсы (zip)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides',
                                            to='materials.level')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
