# Generated by Django 5.1.7 on 2025-04-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('short_description', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('cover', models.ImageField(blank=True, upload_to='courses/covers/', verbose_name='Обложка')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
