# Generated by Django 5.1.7 on 2025-06-24 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['order'], 'verbose_name': 'Методичка', 'verbose_name_plural': 'Методички'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['order'], 'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
    ]
