# Generated by Django 5.1.7 on 2025-04-17 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.FileField(blank=True, help_text='Загрузите SVG файл для обложки', upload_to='courses/covers/',
                                   verbose_name='Обложка'),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название уровня')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels',
                                             to='materials.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название методички')),
                ('file', models.FileField(upload_to='guides/', verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides',
                                            to='materials.level')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
