# Generated by Django 5.1.7 on 2025-06-27 10:50

from django.db import migrations, models

import materials.models


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0002_alter_course_options_alter_guide_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='folder_slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.FileField(blank=True, upload_to=materials.models.course_cover_upload_path,
                                   verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='assets',
            field=models.FileField(blank=True, null=True, upload_to=materials.models.guide_upload_path,
                                   verbose_name='Ресурсы (zip)'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to=materials.models.guide_upload_path,
                                   verbose_name='HTML файл'),
        ),
    ]
