# Generated by Django 5.1.7 on 2025-04-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0002_alter_course_cover_level_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип уровня')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип уровня',
                'verbose_name_plural': 'Типы уровней',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='order',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_advanced',
            field=models.BooleanField(default=False, verbose_name='Есть продвинутый уровень'),
        ),
        migrations.AddField(
            model_name='course',
            name='has_preparatory',
            field=models.BooleanField(default=False, verbose_name='Есть подготовительный уровень'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.FileField(blank=True, upload_to='courses/covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название курса'),
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_levels',
                                             to='materials.course')),
                ('level_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.leveltype',
                                                 verbose_name='Тип уровня')),
            ],
            options={
                'verbose_name': 'Уровень курса',
                'verbose_name_plural': 'Уровни курсов',
                'ordering': ['course', 'level_type__order'],
                'unique_together': {('course', 'level_type')},
            },
        ),
        migrations.AlterField(
            model_name='guide',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides',
                                    to='materials.courselevel'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
