# Generated by Django 5.1.7 on 2025-04-17 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0003_leveltype_alter_course_options_remove_course_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courselevel',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='courselevel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courselevel',
            name='level_type',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveField(
            model_name='course',
            name='has_advanced',
        ),
        migrations.RemoveField(
            model_name='course',
            name='has_preparatory',
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название уровня')),
                ('description', models.TextField(blank=True, verbose_name='Описание уровня')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels',
                                             to='materials.course')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('course', 'title')},
            },
        ),
        migrations.AlterField(
            model_name='guide',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides',
                                    to='materials.level'),
        ),
        migrations.DeleteModel(
            name='LevelType',
        ),
        migrations.DeleteModel(
            name='CourseLevel',
        ),
    ]
