# Generated by Django 5.1.7 on 2025-06-28 18:20

from django.db import migrations, models

import materials.models


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0003_course_folder_slug_alter_course_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='assets',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=materials.models.guide_upload_path,
                                   verbose_name='Ресурсы (zip)'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='html_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=materials.models.guide_upload_path,
                                   verbose_name='HTML файл'),
        ),
    ]
