# Generated by Django 5.1.7 on 2025-09-10 19:59

from django.db import migrations, models

import materials.models


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0004_alter_guide_assets_alter_guide_html_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='assets',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=materials.models.guide_upload_path,
                                   verbose_name='Ресурсы (zip с изображениями)'),
        ),
    ]
