# Generated by Django 5.1.7 on 2025-04-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materials', '0004_alter_courselevel_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='file',
        ),
        migrations.AddField(
            model_name='guide',
            name='assets',
            field=models.FileField(blank=True, null=True, upload_to='guides/assets/', verbose_name='Ресурсы (zip)'),
        ),
        migrations.AddField(
            model_name='guide',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='guides/html/', verbose_name='HTML файл'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
